import type { FrequencyProfile } from '@/lib/types';

export function getStabilityLabel(stability: number): string {
  if (stability >= 0.85) return 'Locked';
  if (stability >= 0.6) return 'Steady';
  if (stability >= 0.3) return 'Variable';
  return 'Unstable';
}

export function getRichnessLabel(richness: number): string {
  if (richness >= 60) return 'Rich';
  if (richness >= 35) return 'Moderate';
  return 'Thin';
}

export function getInstrumentSuggestion(richness: number): string {
  if (richness > 50) {
    return 'Rich overtone voice — warm, sustained tones. Monochord and singing bowls.';
  }
  return 'Thinner profile — complement with harmonically rich instruments. Gongs and didgeridoo.';
}

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatCents(cents: number): string {
  if (cents === 0) return '±0';
  return cents > 0 ? `+${cents}` : `${cents}`;
}

/**
 * Generate the email body for the mailto: link.
 */
export function formatEmailSubject(profile: FrequencyProfile): string {
  return `Frequency Profile — ${profile.noteInfo.note}${profile.noteInfo.octave} ${profile.fundamental}Hz — ${profile.chakra.name} Chakra`;
}

export function formatEmailBody(profile: FrequencyProfile): string {
  const { noteInfo, chakra, stability, richness, fifth, third, fundamental, voiceProfile } = profile;

  return `HARMONIC INTAKE — Frequency Profile
${formatDate(profile.timestamp)} ${formatTime(profile.timestamp)}

FUNDAMENTAL
Frequency: ${fundamental} Hz
Note: ${noteInfo.note}${noteInfo.octave} (${formatCents(noteInfo.cents)} cents)
Chakra: ${chakra.name} — ${chakra.intention}
Stability: ${Math.round(stability * 100)}% (${getStabilityLabel(stability)})
Overtone Richness: ${richness}% (${getRichnessLabel(richness)})

VOICE BIOMARKERS
Jitter: ${voiceProfile.jitter.relative.toFixed(2)}%
Shimmer: ${voiceProfile.shimmer.db.toFixed(2)} dB
HNR: ${voiceProfile.hnr} dB
Pitch Range: ${voiceProfile.pitchRange.rangeSemitones} semitones
Formants: F1=${voiceProfile.formants.f1}Hz F2=${voiceProfile.formants.f2}Hz F3=${voiceProfile.formants.f3}Hz

SESSION RECOMMENDATIONS
Drone note: ${noteInfo.note}${noteInfo.octave}
Perfect 5th: ${fifth.note.note}${fifth.note.octave} (${fifth.freq} Hz) — for expansion
Minor 3rd: ${third.note.note}${third.note.octave} (${third.freq} Hz) — for emotional release

${getInstrumentSuggestion(richness)}

Focus intention: ${chakra.intention}

This analysis explores the acoustic qualities of your voice through a wellness lens. It is not a medical, diagnostic, or clinical assessment.

— Generated by Harmonic Intake`;
}

/**
 * Generate the shorter clipboard text format.
 */
export function formatClipboardText(profile: FrequencyProfile): string {
  const { noteInfo, chakra, stability, richness, fifth, third, fundamental, voiceProfile } = profile;

  return `HARMONIC INTAKE — Frequency Profile

Fundamental: ${fundamental} Hz (${noteInfo.note}${noteInfo.octave})
Chakra: ${chakra.name} — ${chakra.intention}
Stability: ${Math.round(stability * 100)}%
Overtone Richness: ${richness}%
HNR: ${voiceProfile.hnr} dB | Jitter: ${voiceProfile.jitter.relative.toFixed(2)}%

Drone: ${noteInfo.note}${noteInfo.octave} | 5th: ${fifth.note.note}${fifth.note.octave} | m3: ${third.note.note}${third.note.octave}`;
}
